feat: handle faqs with markdown
boxfish-studio/www.tlip.io pull request #58
Opened 2023-06-14 10:45 UTC by VmMad

Fixes #56

2023-06-14 11:38 UTC, begonaalvarezd requested changes
Code looks amazing great job!
Havent tested it yet though
Added a mini comment

2023-06-14 11:38 UTC, begonaalvarezd commented on src/lib/utils.ts
> +export function parseMarkdownToFaqs(html: string): FaqSection[] {
we could try having this function a bit more generic so h2 & h3 are not the only headings allowed. You have an example in the assembly repo 🙏🏼 https://github.com/boxfish-studio/assembly-website/blob/main/src/components/indexed-section.svelte#L36

2023-06-15 08:48 UTC, begonaalvarezd requested changes
Testing the code I saw that not all FAQs are rendered, some are empty. 
Please review that everything displays like in production 🙏🏼 

![image](https://github.com/boxfish-studio/www.tlip.io/assets/3624944/0b15a609-09c8-45c0-81e4-537898f73c40)
![image](https://github.com/boxfish-studio/www.tlip.io/assets/3624944/3db7c338-daca-41a2-97e6-e03f8936371f)
![image](https://github.com/boxfish-studio/www.tlip.io/assets/3624944/9e1007ed-7465-4d69-bf04-8f4e793e031d)
![image](https://github.com/boxfish-studio/www.tlip.io/assets/3624944/9f62a495-3842-4c15-9d4e-2027d10a4637)

2023-06-15 09:26 UTC, evavirseda commented
> Testing the code I saw that not all FAQs are rendered, some are empty. Please review that everything displays like in production 🙏🏼
> 
> ![image](https://user-images.githubusercontent.com/3624944/246050401-0b15a609-09c8-45c0-81e4-537898f73c40.png) ![image](https://user-images.githubusercontent.com/3624944/246050447-3db7c338-daca-41a2-97e6-e03f8936371f.png) ![image](https://user-images.githubusercontent.com/3624944/246050473-9e1007ed-7465-4d69-bf04-8f4e793e031d.png) ![image](https://user-images.githubusercontent.com/3624944/246050531-9f62a495-3842-4c15-9d4e-2027d10a4637.png)

I had the same experience, and I think this could be resolved by removing the `else` and making sure that the level is `>= firstHeadingLevel`. That way, we'll have the first heading included as well. However, we can remove it later. I hope this helps :smiley: :pray:

2023-06-27 13:17 UTC, begonaalvarezd approved these changes

2023-06-27 13:18 UTC, merged